### ISSUE TITLE
Missing object.ifo

### ISSUE THREAD

**Issue by love1106** [tanisman/SilkroadProject#1]
Missing file object.ifo when try to read : 
Path.Combine(Environment.CurrentDirectory, "data\navmesh\object.ifo")

**Comment by tanisman** [comment]
you must extract client's Data.pk2 to data/ folder

**Comment by love1106** [comment]
Thank for help, and for the updating readme file :)

**Comment by love1106** [comment]
I have some questions, please help me when you have time :
With the client : do i have to extract all pk2 file : data, map, media, music and Particles?
If i run in local, i change ip address to 127.0.0.1, is it correct?
Everything seems works good but i don't see any server when open client laucher. Do i miss something?

**Comment by love1106** [comment]
today i can join the game but the char can't able to attack the mob.

**Comment by tanisman** [comment]
Hello, currently the emulator is on development progress.We havent made any action releated feature yet
